title: Charles Wang # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Charles a second-year student at the University of Waterloo studying Geospatial Data Science as my major and minoring in Computing. I love video games and solving problems, 
  sometimes the two coincide and result in the creation of my projects. This page is simply a portfolio to display the projects that I have built.
  <br><br>
  <a href="https://www.linkedin.com/in/charles-wang-8228243a8/">View My LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
